apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io: {{ .Release.Name }}
  name: {{ .Release.Name }}-unfinkme-slackbot
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - host: {{ .Values.hostUri }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: 8080
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - {{ .Values.hostUri }}
      secretName: {{ .Values.tlsSecretName }}
