apiVersion: v1
data:
  BOT_CHANNEL: {{ .Values.botChannel }}
  SLACK_API_TOKEN: {{ .Values.slackApiToken }}
  SLACK_BOT_ID: {{ .Values.slackBotId }}
  SLACK_CHANNEL_ID: {{ .Values.slackChannelId }}
  SLACK_SIGNING_SECRET: {{ .Values.slackSigningSecret }}
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
